name = "kmd" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = ".fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "blog.sushiroll.co.id.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "www.sushiroll.co.id.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "api.joox.com.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "www.joox.com.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "investor.spotify.com.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "layanan.ruangguru.com.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "104.18.3.2.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "162.159.138.6.kmd.fadztunnell.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.kmd.fadztunnell.my.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "77f8c412-e65e-45b0-88e8-ef710acc926c"
