name = "fadtech2" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "www.sushiroll.co.id.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "blog.sushiroll.co.id.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "cdn.appsflyer.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "www.joox.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "zoomcares.zoom.us.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "graph.facebook.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "www.help.tinder.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "poe.garena.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "games.axis.co.id.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "api.ovo.id.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "cdnodeb.visionplus.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "104.26.6.171.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "go.appsflyer.com.fadztechq.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "devsupport.webex.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "edu.ruangguru.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "fadz.ngapaktunnelling.xyz.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "creativeservices.netflix.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "npca.netflix.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "gw.ruangguru.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "edu.udemy.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "z-p4.www.instagram.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "web.poe.garena.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "static.cdninstagram.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "dl.cvs.freefiremobile.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "104.17.74.206.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "104.17.3.81.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "sogood.linefriends.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "104.18.29.141.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "layanan.ruangguru.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "104.16.51.111.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "help.pornhub.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "162.159.130.11.fadztech1.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "162.159.138.6.fadztech1.ngapaktunnelling.xyz"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "4819b8b0-6a33-4c6c-8d33-c0947ecbe803"
